SET NOCOUNT ON;

SELECT
    r.ROUTINE_SCHEMA + '.' + r.ROUTINE_NAME AS routine_name,
    CAST(COUNT(p.PARAMETER_NAME) AS varchar(10)) AS parameter_count,
    COALESCE(
        STRING_AGG(COALESCE(p.DATA_TYPE, ''), ', ') WITHIN GROUP (ORDER BY p.ORDINAL_POSITION),
        ''
    ) AS parameter_types,
    COALESCE(r.DATA_TYPE, '') AS return_type
FROM INFORMATION_SCHEMA.ROUTINES AS r
LEFT JOIN INFORMATION_SCHEMA.PARAMETERS AS p
    ON p.SPECIFIC_SCHEMA = r.SPECIFIC_SCHEMA
   AND p.SPECIFIC_NAME = r.SPECIFIC_NAME
   AND p.ORDINAL_POSITION > 0
WHERE r.ROUTINE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
  AND r.ROUTINE_TYPE = 'FUNCTION'
GROUP BY r.ROUTINE_SCHEMA, r.ROUTINE_NAME, r.SPECIFIC_SCHEMA, r.SPECIFIC_NAME, r.DATA_TYPE
ORDER BY routine_name, parameter_count;
