SET NOCOUNT ON;

SELECT
    v.TABLE_SCHEMA + '.' + v.TABLE_NAME AS view_name,
    COALESCE(
        STRING_AGG(c.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY c.ORDINAL_POSITION),
        ''
    ) AS view_columns
FROM INFORMATION_SCHEMA.VIEWS AS v
LEFT JOIN INFORMATION_SCHEMA.COLUMNS AS c
    ON c.TABLE_SCHEMA = v.TABLE_SCHEMA
   AND c.TABLE_NAME = v.TABLE_NAME
WHERE v.TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
GROUP BY v.TABLE_SCHEMA, v.TABLE_NAME
ORDER BY view_name;
